package org.sang.mapper;

import org.sang.bean.CompanyData;

public interface CompanyDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_data
     *
     * @mbg.generated Wed Jun 05 16:32:28 CST 2019
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_data
     *
     * @mbg.generated Wed Jun 05 16:32:28 CST 2019
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_data
     *
     * @mbg.generated Wed Jun 05 16:32:28 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_data
     *
     * @mbg.generated Wed Jun 05 16:32:28 CST 2019
     */
    int insert(CompanyData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_data
     *
     * @mbg.generated Wed Jun 05 16:32:28 CST 2019
     */
    int insertSelective(CompanyData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_data
     *
     * @mbg.generated Wed Jun 05 16:32:28 CST 2019
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_data
     *
     * @mbg.generated Wed Jun 05 16:32:28 CST 2019
     */
    CompanyData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_data
     *
     * @mbg.generated Wed Jun 05 16:32:28 CST 2019
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_data
     *
     * @mbg.generated Wed Jun 05 16:32:28 CST 2019
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_data
     *
     * @mbg.generated Wed Jun 05 16:32:28 CST 2019
     */
    int updateByPrimaryKeySelective(CompanyData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_data
     *
     * @mbg.generated Wed Jun 05 16:32:28 CST 2019
     */
    int updateByPrimaryKey(CompanyData record);
}