package org.sang.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.sang.bean.Folder;

public interface FolderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbg.generated Wed Jun 05 16:32:28 CST 2019
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbg.generated Wed Jun 05 16:32:28 CST 2019
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbg.generated Wed Jun 05 16:32:28 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbg.generated Wed Jun 05 16:32:28 CST 2019
     */
    int insert(Folder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbg.generated Wed Jun 05 16:32:28 CST 2019
     */
    int insertSelective(Folder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbg.generated Wed Jun 05 16:32:28 CST 2019
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbg.generated Wed Jun 05 16:32:28 CST 2019
     */
    Folder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbg.generated Wed Jun 05 16:32:28 CST 2019
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbg.generated Wed Jun 05 16:32:28 CST 2019
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbg.generated Wed Jun 05 16:32:28 CST 2019
     */
    int updateByPrimaryKeySelective(Folder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbg.generated Wed Jun 05 16:32:28 CST 2019
     */
    int updateByPrimaryKey(Folder record);
    
    List<Folder> getAllFolder();
    
    List<Folder> getChirdFolder(int ParentId);
}