package org.sang.bean;

import java.util.Date;

public class Folder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.id
     *
     * @mbg.generated Wed Jun 05 16:32:28 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.folder_name
     *
     * @mbg.generated Wed Jun 05 16:32:28 CST 2019
     */
    private String folderName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.company_id
     *
     * @mbg.generated Wed Jun 05 16:32:28 CST 2019
     */
    private Integer companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.staff_id
     *
     * @mbg.generated Wed Jun 05 16:32:28 CST 2019
     */
    private Integer staffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.parent_id
     *
     * @mbg.generated Wed Jun 05 16:32:28 CST 2019
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column folder.create_time
     *
     * @mbg.generated Wed Jun 05 16:32:28 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.id
     *
     * @return the value of folder.id
     *
     * @mbg.generated Wed Jun 05 16:32:28 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.id
     *
     * @param id the value for folder.id
     *
     * @mbg.generated Wed Jun 05 16:32:28 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.folder_name
     *
     * @return the value of folder.folder_name
     *
     * @mbg.generated Wed Jun 05 16:32:28 CST 2019
     */
    public String getFolderName() {
        return folderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.folder_name
     *
     * @param folderName the value for folder.folder_name
     *
     * @mbg.generated Wed Jun 05 16:32:28 CST 2019
     */
    public void setFolderName(String folderName) {
        this.folderName = folderName == null ? null : folderName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.company_id
     *
     * @return the value of folder.company_id
     *
     * @mbg.generated Wed Jun 05 16:32:28 CST 2019
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.company_id
     *
     * @param companyId the value for folder.company_id
     *
     * @mbg.generated Wed Jun 05 16:32:28 CST 2019
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.staff_id
     *
     * @return the value of folder.staff_id
     *
     * @mbg.generated Wed Jun 05 16:32:28 CST 2019
     */
    public Integer getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.staff_id
     *
     * @param staffId the value for folder.staff_id
     *
     * @mbg.generated Wed Jun 05 16:32:28 CST 2019
     */
    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.parent_id
     *
     * @return the value of folder.parent_id
     *
     * @mbg.generated Wed Jun 05 16:32:28 CST 2019
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.parent_id
     *
     * @param parentId the value for folder.parent_id
     *
     * @mbg.generated Wed Jun 05 16:32:28 CST 2019
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column folder.create_time
     *
     * @return the value of folder.create_time
     *
     * @mbg.generated Wed Jun 05 16:32:28 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column folder.create_time
     *
     * @param createTime the value for folder.create_time
     *
     * @mbg.generated Wed Jun 05 16:32:28 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}